name: Build and Lint

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.6'

    - name: Install dependencies
      run: |
        go mod download

    - name: Run Server
      run: make

    - name: Send Request
      run: |
        API_URL="http://127.0.0.1:8080/status"
        STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" $API_URL)
        if [ $STATUS_CODE -eq 200 ]; then
            echo "API is deployed and responding with status code 200 (OK)"
        else
            echo "Error: API deployment failed. Received status code: $STATUS_CODE"
             exit 1
        fi
